title: sciml-edinburgh
description: Scientific Machine Learning at UNiversity of Edinburgh

# OPTIONAL: override baseurl and url if using a custom domain
# Note: leave out the trailing / from this value. 
url: "https://sciml-edinburgh.github.io" # the base hostname & protocol for your site, e.g. http://example.com
